{
 "title": "orders service export",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Order cancellation result",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orders_service_orders_cancellation_result",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Order cancellation by initial status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orders_service_orders_cancelled_from_status",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "grpc response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(orders_service_grpc_response_time_bucket[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "system runtime cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}